version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=appartmants_db
      - POSTGRES_USER=merdan
      - POSTGRES_PASSWORD=353062
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5410:5432"

volumes:
  db: